<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.2 setup script
 * Date: Wed, 04 Jun 2025 02:26:00 +0000
 */

$servername = 'vergil.u.washington.edu'; // Your Server (if noot)
$username = 'root';
$password = 'CSS475CashMeal';
$database = 'CashMeal';
$port = 27682; // Your Port